[package]
name = "biding-writer"
version = "0.1.0"
edition = "2018"
authors = ["viv <vvnl+git@protonmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
